#!/usr/bin/env bash

BASEDIR=$(dirname "$0")

source ${BASEDIR}/.env

export REACT_APP_CLIENT=${REACT_APP_CLIENT}
export REACT_APP_POCKETBASE_ADMIN_USERNAME=${REACT_APP_POCKETBASE_ADMIN_USERNAME}
export REACT_APP_POCKETBASE_ADMIN_PASSWORD=${REACT_APP_POCKETBASE_ADMIN_PASSWORD}
export PORT=${PORT}

yarn run start