
name: Continuous Integration (CI)

on:
  push:
    branches:
      # We can define multiple branches as well      
      - main
  pull_request:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn run build --if-present
      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          yarn run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'